---

- hosts: all
  become: true
  vars_files:
  - variables/vars.yml
  tasks:


  - name: Checking if git already exists in the system
    package_facts:
      manager: "auto"
    tags:
    - tag1

  - name: Installing Git 
    yum: 
      name: git
      state: present
    when: "'git' not in ansible_facts.packages"
    tags:
    - tag2
  

  - name: installing "lsof" command
    yum: 
      name: lsof
      state: present
    when: "'lsof' not in ansible_facts.packages"
    tags:
    - tag3


  - name: Creating node_exporter user group
    group: name="{{ group_node }}"
    become: true
    tags:
    - tag4
    

  - name: Creating node_exporter user
    user:
      name: "{{ user_node }}"
      group: "{{ group_node }}"
      system: yes
      shell: "/sbin/nologin"
      comment: "{{ user_node }} nologin User"
      createhome: "no"
      state: present
    tags:
    - tag5
  

  - name: Install "node-exporter"
    unarchive:
      src: "https://github.com/prometheus/node_exporter/releases/download/v{{version_node}}/node_exporter-{{version_node}}.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes
    tags:
    - tag6

 
  - name: Copy prometheus node exporter file to /usr/local/bin
    copy:
      src: "/tmp/node_exporter-{{version_node}}.linux-amd64/node_exporter"
      dest: "/usr/local/bin/node_exporter"
      owner: "{{ user_node }}"
      group: "{{ group_node }}"
      remote_src: yes
      mode: 0755
    tags:
    - tag7


  - name: Delete node exporter tmp folder
    file:
      path: '/tmp/node_exporter-{{version_node}}.linux-amd64'
      state: absent
    tags:
    - tag8
        

  - name: Copy systemd init file
    template:
      src: services/exporter.service
      dest: /etc/systemd/system/node_exporter.service
    tags:
    - tag9
 
 
  - name: Start node_exporter service
    service:
      name: node_exporter
      state: started
      enabled: yes
    tags:
    - tag10
